// <auto-generated />
namespace Zanella.ORM.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cpf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cpf));
        
        string IMigrationMetadata.Id
        {
            get { return "201807172043388_cpf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
